Add support to load model within torch._subclasses.FakeTensorMode
Currently, when a user tries to load a model under Pytorch's FakeTensorMode,
`result[k] = f.get_tensor(k)` fails with a `ValueError` that says
`could not determine the shape of object type 'torch.storage.UntypedStorage'`

This happens because `FakeTensor` does not have actual data to be loaded

This PR tries to detect a fake mode and when one is found, an empty
tensor is created with the original shape and type - no data is actually
loaded

Repro:

```python
from torch._subclasses.fake_tensor import FakeTensorMode
from transformers import AutoModel

model_name = "bigscience/bloom-560m"
fake_mode = FakeTensorMode()
with fake_mode:
    model = AutoModel.from_pretrained(model_name)
```

Error:

```bash
[2023-08-09 17:20:39,037] [INFO] [real_accelerator.py:110:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Traceback (most recent call last):
  File "/opt/pytorch/repro_bloom.py", line 12, in <module>
    model = AutoModel.from_pretrained(model_name)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2629, in from_pretrained
    state_dict = load_state_dict(resolved_archive_file)
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/transformers/modeling_utils.py", line 458, in load_state_dict
    return safe_load_file(checkpoint_file)
  File "/opt/safetensors/bindings/python/py_src/safetensors/torch.py", line 319, in load_file
    result[k] = f.get_tensor(k)
ValueError: could not determine the shape of object type 'torch.storage.UntypedStorage'
```